// Reads data/collection.csv (Discogs export), enriches each release via the
// Discogs API (cover, genres, styles, tracklist, original year) and writes data/collection.js.
// Covers are cached in covers/<release_id>.jpg. Re-run after a new export.
import fs from "node:fs/promises";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const UA = "MyVinyl/1.0 +https://github.com/";
const cachePath = path.join(root, "data/releases-cache.json");

function parseCSV(text) {
  const rows = [];
  let row = [], field = "", q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') q = false;
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.some(Boolean)) rows.push(row);
      row = [];
    } else field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  const [head, ...body] = rows;
  return body.map(r => Object.fromEntries(head.map((h, i) => [h, r[i] ?? ""])));
}

const sleep = ms => new Promise(r => setTimeout(r, ms));
const clean = s => s.replace(/\s\(\d+\)$/, ""); // "Cream Soda (2)" -> "Cream Soda"

async function fetchRelease(id) {
  for (let attempt = 0; attempt < 5; attempt++) {
    const res = await fetch(`https://api.discogs.com/releases/${id}`, { headers: { "User-Agent": UA } });
    if (res.status === 429) { await sleep(15000); continue; }
    if (!res.ok) throw new Error(`release ${id}: HTTP ${res.status}`);
    return res.json();
  }
  throw new Error(`release ${id}: rate limited`);
}

const csv = parseCSV(await fs.readFile(path.join(root, "data/collection.csv"), "utf8"));
let cache = {};
try { cache = JSON.parse(await fs.readFile(cachePath, "utf8")); } catch {}

const out = [];
for (const r of csv) {
  const id = r.release_id;
  if (!cache[id]) {
    process.stdout.write(`fetch ${id} ${r.Artist} – ${r.Title}\n`);
    const d = await fetchRelease(id);
    cache[id] = {
      genres: d.genres || [], styles: d.styles || [], country: d.country || "",
      uri: d.uri, image: (d.images?.find(i => i.type === "primary") || d.images?.[0])?.uri || "",
      tracklist: (d.tracklist || []).filter(t => t.type_ === "track")
        .map(t => ({ pos: t.position, title: t.title, dur: t.duration })),
    };
    if (d.master_id) {
      // The export's "Released" is the pressing year; the master release holds the original year.
      await sleep(2600);
      const res = await fetch(`https://api.discogs.com/masters/${d.master_id}`, { headers: { "User-Agent": UA } });
      if (res.ok) cache[id].originalYear = (await res.json()).year || null;
    }
    cache[id].originalYear ||= d.year || null;
    await fs.writeFile(cachePath, JSON.stringify(cache, null, 1));
    await sleep(2600); // unauthenticated limit: 25 req/min
  }
  const c = cache[id];
  const cover = `covers/${id}.jpg`;
  try { await fs.access(path.join(root, cover)); }
  catch {
    if (c.image) {
      const res = await fetch(c.image, { headers: { "User-Agent": UA } });
      if (res.ok) await fs.writeFile(path.join(root, cover), Buffer.from(await res.arrayBuffer()));
      await sleep(500);
    }
  }
  let hasCover = true;
  try { await fs.access(path.join(root, cover)); } catch { hasCover = false; }

  out.push({
    id: Number(id), artist: clean(r.Artist), title: r.Title, label: r.Label.split(",").map(s => clean(s.trim())).join(", "),
    catno: r["Catalog#"], format: r.Format, year: Number(r.Released) || null,
    added: r["Date Added"].slice(0, 10), condition: r["Collection Media Condition"], notes: r["Collection Notes"],
    cover: hasCover ? cover : null, ...c, image: undefined,
  });
}

await fs.writeFile(path.join(root, "data/collection.js"),
  `// Generated by scripts/build-data.mjs — do not edit by hand.\nwindow.COLLECTION = ${JSON.stringify(out, null, 1)};\n`);
console.log(`wrote ${out.length} records`);
